import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
  <meta
    name="google-site-verification"
    content="9u8sSV5dehSez5o5_FH_Sq27tSw000IvIuqyQ6FDekQ"
  />
</head>

      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
